ECommerce/Controllers/ProductController.cs
using ECommerce.BLL.Services.Contracts;
using ECommerce.DAL.DataContext.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace  ECommerce.MVC.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Details(string id)
        {
            int productId = int.Parse(id.Split('-').Last());

            var model = await _productService.GetAsync(predicate: x => x.Id == productId && !x.IsDeleted,
                include: x => x
                .Include(c => c.Category)
                .Include(pv => pv.ProductImages));

            return View(model);
        }
    }
}

ECommerce/ViewComponents/FooterViewComponent.cs
using ECommerce.BLL.Services.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.MVC.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        private readonly IFooterService _footerService;

        public FooterViewComponent(IFooterService footerService)
        {
            _footerService = footerService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = await _footerService.GetFooterAsync();
            return View(model);
        }
    }
}

ECommerce/ViewComponents/HeaderViewComponent.cs
using ECommerce.BLL.Services.Contracts;
using ECommerce.BLL.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ECommerce.MVC.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly IHeaderService _headerService;

        public HeaderViewComponent(IHeaderService headerService)
        {
            _headerService = headerService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = await _headerService.GetHeaderAsync();

            return View(model);
        }
    }
}

ECommerce/Views/Shared/_AccountMenuPartial.cshtml
<div class="wrap-sidebar-account">
    <ul class="my-account-nav">
        <li><a asp-controller="account" asp-action="index"><span class="my-account-nav-item active">Dashboard</span></a></li>
        <li><a asp-controller="account" asp-action="orders" class="my-account-nav-item">Orders</a></li>
        <li><a asp-controller="account" asp-action="address" class="my-account-nav-item">Address</a></li>
        <li><a asp-controller="account" asp-action="edit" class="my-account-nav-item">Account Details</a></li>
        <li><a asp-controller="account" asp-action="wishlist" class="my-account-nav-item">Wishlist</a></li>
        <li><a asp-account="account" asp-action="logout" class="my-account-nav-item">Logout</a></li>
    </ul>
</div>

ECommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">


<!-- Mirrored from themesflat.co/html/ecomus/home-supplement.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 18 Jul 2025 16:14:34 GMT -->
<head>
    <meta charset="utf-8">
    <title>Ecomus - Ultimate HTML</title>

    <meta name="author" content="themesflat.com">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description"
          content="Themesflat Ecomus - A modern and versatile eCommerce template designed for various online stores, including fashion, furniture, electronics, and more. SEO-friendly, fast-loading, and highly customizable.">

    <!-- font -->
    <link rel="stylesheet" href="~/fonts/fonts.css">
    <!-- Icons -->
    <link rel="stylesheet" href="~/fonts/font-icons.css">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/swiper-bundle.min.css">
    <link rel="stylesheet" href="~/css/animate.css">
    <link rel="stylesheet" href="~/../../../sibforms.com/forms/end-form/build/sib-styles.css">
    <link rel="stylesheet" type="text/css" href="~/css/styles.css" />

    <!-- Favicon and Touch Icons  -->
    <link rel="shortcut icon" href="~/images/logo/favicon.png">
    <link rel="apple-touch-icon-precomposed" href="~/images/logo/favicon.png">

</head>

<body class="preload-wrapper color-primary-15">

@await Component.InvokeAsync("Header")

@RenderBody()

@await Component.InvokeAsync("Footer")


<!-- Javascript -->
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/swiper-bundle.min.js"></script>
    <script src="~/js/carousel.js"></script>
    <script src="~/js/bootstrap-select.min.js"></script>
    <script src="~/js/lazysize.min.js"></script>
    <script src="~/js/bootstrap-select.min.js"></script>
    <script type="module" src="~/js/image-compare-viewer.js"></script>
    <script src="~/js/wow.min.js"></script>
    <script src="~/js/multiple-modal.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/shop.js"></script>
    <script src="~/js/nouislider.min.js"></script>
    <script src="~/js/basket.js" asp-append-version="true"></script>
    <script src="~/js/load-more.js" asp-append-version="true"></script>


</body>


<!-- Mirrored from themesflat.co/html/ecomus/home-supplement.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 18 Jul 2025 16:14:43 GMT -->
</html>

ECommerce/Views/Shared/_ProductCardPartial.cshtml
@model IEnumerable<ProductViewModel>

@foreach (var product in Model)
{
    <div class="card-product loadItem grid">
        <a asp-controller="Product" asp-action="Details" asp-route-id="@product.DetailsUrl" class="product-img">
            <img src="~/images/products/@product.CoverImageName" alt="@product.Name" />
        </a>
        <div class="card-product-info">
            <a asp-controller="Product" asp-action="Details" asp-route-id="@product.DetailsUrl" class="title link">@product.Name</a>
            <span class="price">$@product.BasePrice</span>
        </div>
    </div>
}

ECommerce/Views/Shared/_ProductListPartial.cshtml
@model IEnumerable<ProductViewModel>

@foreach (var product in Model)
{
    <div class="card-product grid">
        <div class="card-product-wrapper">
            <a asp-controller="product" asp-action="details" asp-route-id="@product.DetailsUrl" class="product-img">
                <img src="~/images/products/@product.CoverImageName" alt="@product.Name" />
                @{
                    var picture = product.Images.FirstOrDefault();
                }
                @if (picture != null)
                {
                    <img class="img-hover" src="~/images/products/@picture.ImageName" alt="@product.Name" />
                }
            </a>
        </div>
        <div class="card-product-info">
            <a asp-controller="product" asp-action="details" asp-route-id="@product.DetailsUrl" class="title link">@product.Name</a>
            <span class="price">$@product.BasePrice</span>
        </div>
    </div>
}